name: id_schema tests

on:
  pull_request:
  push:
    branches: [master, test-me-*]

jobs:
  test:
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependencies
        run: python -m pip install --upgrade tox virtualenv setuptools pip
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: true
          verbose: true
